-- Tabela korisnika (public) + bezbedna prijava preko RPC (bez javnog SELECT-a lozinki)

create table if not exists public.korisnici (
  id bigint generated by default as identity not null,
  naziv character varying not null default '100'::character varying,
  email character varying null default '100'::character varying,
  password character varying null default '100'::character varying,
  brojmob character varying null default '50'::character varying,
  stsstatus character varying null default ''::character varying,
  stsaktivan character varying null default ''::character varying,
  datumk timestamp with time zone null,
  datump timestamp with time zone null,
  datumpt timestamp with time zone null default now(),
  adresa text null,
  constraint korisnici_pkey primary key (id),
  constraint korisnici_stsaktivan_check check (
    (stsaktivan is null)
    or ((stsaktivan)::text = any (array[('da'::character varying)::text, ('ne'::character varying)::text]))
  ),
  constraint korisnici_stsstatus_check check (
    (stsstatus is null)
    or (
      (stsstatus)::text = any (
        array[
          ('kupac'::character varying)::text,
          ('prodavac'::character varying)::text,
          ('agent'::character varying)::text,
          ('admin'::character varying)::text,
          ('manager'::character varying)::text
        ]
      )
    )
  )
);

alter table public.korisnici enable row level security;

-- Nema politika SELECT za anon — pristup samo preko funkcije ispod

create or replace function public.login_korisnik(p_email text, p_password text)
returns table (
  id bigint,
  naziv character varying,
  email character varying,
  stsstatus character varying
)
language sql
security definer
set search_path = public
as $$
  select k.id, k.naziv, k.email, k.stsstatus
  from public.korisnici k
  where
    (trim(both from coalesce(k.email, '')) = trim(both from p_email)
      or trim(both from coalesce(k.naziv, '')) = trim(both from p_email))
    and k.password = p_password
    and (k.stsaktivan is null or trim(both from k.stsaktivan) = 'da')
  limit 1;
$$;

revoke all on public.korisnici from anon, authenticated;
grant select, insert, update, delete on table public.korisnici to service_role;

grant execute on function public.login_korisnik(text, text) to anon, authenticated;

-- Podrazumevani nalog za formu (email/korisničko ime: grabovica-janjici, lozinka: 1234567gr)
insert into public.korisnici (naziv, email, password, stsstatus, stsaktivan)
select
  'Administrator',
  'grabovica-janjici',
  '1234567gr',
  'admin',
  'da'
where not exists (
  select 1 from public.korisnici k
  where trim(both from coalesce(k.email, '')) = 'grabovica-janjici'
);
